### ISSUE TITLE
BUG UI拖拽BUG；

### ISSUE THREAD

**Issue by Lionad-Morotar** [mockingbot/A-sketch-like-color-picker-in-javascript#6]
# BUG

## 1. UI错误

![image](https://user-images.githubusercontent.com/26913795/42423426-8c36f8c8-832c-11e8-9149-fd3d238bce34.png)

## 2.拖拽问题

![2018-07-09_04-01-49](https://user-images.githubusercontent.com/26913795/42423473-61c0e968-832d-11e8-9fca-fd64fd0f31ee.gif)

### 描述

当鼠标点击不放，将鼠标拖拽出DIV框框外再松手，如下图：
![image](https://user-images.githubusercontent.com/26913795/42423440-c281db6e-832c-11e8-8339-f2487af0b687.png)
此时，若是再次尝试拖拽：
![image](https://user-images.githubusercontent.com/26913795/42423449-f09d044c-832c-11e8-9460-4788308bb704.png)
则会复制出一个空行字符，如下console：
![image](https://user-images.githubusercontent.com/26913795/42423453-0a7fbcc4-832d-11e8-8aff-f59265c0abcc.png)
此外，此时如果不进行拖拽，color-circle 仍然会跟随鼠标移动。

### 解决

如果组件后续没有对拖拽功能作更多要求（如：从canvas-pane拖拽复制颜色值），可以通过禁用DIV canvas-pane的拖拽属性防止复制空行：
```
ondragstart="return false;"
```

## 浏览器环境
360极速浏览器 - 极速模式
![image](https://user-images.githubusercontent.com/26913795/42423361-88da2408-832b-11e8-8df5-0bb76418a8bd.png)

**Comment by Xdudu** [comment]
你好，我们最近更新了代码，由于 API 和 UI 均有较大变化，发布为新包`mb-react-color-picker`。
相信在视觉和功能上都有较大改善，欢迎你再关注一下～
