### ISSUE TITLE
Document Wanted!

### ISSUE THREAD

**Issue by cctv1005s** [mockingbot/A-sketch-like-color-picker-in-javascript#7]
Do you have a plan to make a document or README?
A document is necessary for a opensource project. 

不考虑完善一下文档或者README吗？
开源组件还是需要写一下文档的吧...

**Comment by Xdudu** [comment]
Hi there! We just update a new version, and documentation is implemented as well. API is quite different as before, so we publish a new package to npm, naming `mb-react-color-picker`.

你好～我们最近更新了新版本，文档也有完善。新包名字是`mb-react-color-picker`，API 和 UI 均有较大变化，可以再关注一下。
